export type TDamageType = 
      "Acid"
    | "Bludgeoning"
    | "Cold"
    | "Fire"
    | "Force"
    | "Lightning"
    | "Necrotic"
    | "Piercing"
    | "Poison"
    | "Psychic"
    | "Radiant"
    | "Slashing"
    | "Thunder"
    ;
