import { IItemIndexer } from "../../../Interfaces/IItemIndexer";

export const ItemMap_Weapons: IItemIndexer =
{
    "Club": {
        title: 'Club',
        body: 'A stout bludgeoning weapon made of oak. Attacks with this weapon deal 1d4 bludgeoning damage. [Properties: Light]',
        iconSource: './images/Item_Shop/Items/Weapons/club.png',
        source: "Official",
        itemCost: 1,
        type: "Weapon",
    },
    "Dagger": {
        title: 'Dagger',
        body: 'A small piercing weapon. Attacks with this weapon deal 1d4 piercing damage. [Properties: Finesse, Light, Thrown (range 20/60)]',
        iconSource: './images/Item_Shop/Items/Weapons/dagger.png',
        source: "Official",
        itemCost: 2,
        type: "Weapon",
    },
    "Greatclub": {
        title: 'Greatclub',
        body: 'A massive bludgeoning weapon. Attacks with this weapon deal 1d8 bludgeoning damage. [Properties: Two-handed]',
        iconSource: './images/Item_Shop/Items/Weapons/greatclub.png',
        source: "Official",
        itemCost: 1,
        type: "Weapon",
    },
    "Handaxe": {
        title: 'Handaxe',
        body: 'A small throwing axe. Attacks with this weapon deal 1d6 slashing damage. [Properties: Light, Thrown (range 20/60)]',
        iconSource: './images/Item_Shop/Items/Weapons/handaxe.png',
        source: "Official",
        itemCost: 5,
        type: "Weapon",
    },
    "Javelin": {
        title: 'Javelin',
        body: 'A long, pointed, throwing weapon. Attacks with this weapon deal 1d6 piercing damage. [Properties: Thrown (range 30/120)]',
        iconSource: './images/Item_Shop/Items/Weapons/javelin.png',
        source: "Official",
        itemCost: 5,
        type: "Weapon",
    },
    "LightHammer": {
        title: 'Light Hammer',
        body: 'A small bludgeoning weapon. Attacks with this weapon deal 1d4 bludgeoning damage. [Properties: Light, Thrown (range 20/60)]',
        iconSource: './images/Item_Shop/Items/Weapons/light_hammer.png',
        source: "Official",
        itemCost: 2,
        type: "Weapon",
    },
    "Mace": {
        title: 'Mace',
        body: 'A bludgeoning weapon. Attacks with this weapon deal 1d6 bludgeoning damage.',
        iconSource: './images/Item_Shop/Items/Weapons/mace.png',
        source: "Official",
        itemCost: 5,
        type: "Weapon",
    },
    "Quarterstaff": {
        title: 'Quarterstaff',
        body: 'A long, bludgeoning weapon made of oak. Attacks with this weapon deal 1d6 bludgeoning damage. [Properties: Versatile (1d8)]',
        iconSource: './images/Item_Shop/Items/Weapons/quarterstaff.png',
        source: "Official",
        itemCost: 1,
        type: "Weapon",
    },
    "Sickle": {
        title: 'Sickle',
        body: 'A curved weapon made of steel. Attacks with this weapon deal 1d4 slashing damage. [Properties: Light]',
        iconSource: './images/Item_Shop/Items/Weapons/sickle.png',
        source: "Official",
        itemCost: 1,
        type: "Weapon",
    },
    "Spear": {
        title: 'Spear',
        body: 'A long, pointed weapon. Attacks with this weapon deal 1d6 piercing damage. [Properties: Thrown (range 20/60), Versatile (1d8)]',
        iconSource: './images/Item_Shop/Items/Weapons/spear.png',
        source: "Official",
        itemCost: 1,
        type: "Weapon",
    },
    "Shortsword": {
        title: 'Shortsword',
        body: 'A short, pointed weapon. Attacks with this weapon deal 1d6 piercing damage. [Properties: Finesse, Light]',
        iconSource: './images/Item_Shop/Items/Weapons/shortsword.png',
        source: "Official",
        itemCost: 10,
        type: "Weapon",
    },
    "SnakeStaff": {
        title: 'Snake Staff',
        body: 'A long oaken staff. The staff is wrapped by the likeness of a clay snake. Attacks with this weapon deal 1d4 bludgeoning damage and 1d4 poison damage.',
        iconSource: './images/Item_Shop/Items/Weapons/Cleric Staff Snake Green.png',
        source: "Homebrew",
        itemCost: 100,
        type: "Weapon",
    },
    "Darts": {
        title: 'Darts',
        body: 'A small thrown weapon. 20 darts line a leather pouch. Attacks with this weapon deal 1d4 piercing damage. [Properties: Finesse, Thrown (range 20/60)]',
        iconSource: './images/Item_Shop/Items/Weapons/dart.png',
        source: "Official",
        itemCost: 1,
        type: "Weapon",
    },
    "LightCrossbow": {
        title: 'Light Crossbow',
        body: 'A light, mechanical device used for firing arrows across large distances. Attacks with this weapon deal 1d8 piercing damage. [Properties: Ammunition (range 80/320), Loading, Two-handed]',
        iconSource: './images/Item_Shop/Items/Weapons/light_crossbow.png',
        source: "Official",
        itemCost: 25,
        type: "Weapon",
    },
    "Shortbow": {
        title: 'Shortbow',
        body: 'A long, curved piece of wood held taut by a length of wire. Attacks with this weapon deal 1d6 piercing damage. [Properties: Ammunition (range 80/320), Two-handed]',
        iconSource: './images/Item_Shop/Items/Weapons/shortbow.png',
        source: "Official",
        itemCost: 25,
        type: "Weapon",
    },
    "Sling": {
        title: 'Sling',
        body: 'A small pocket held by two lengths of rope. When spun quickly, it can hurl projectiles at lethal speed. Attacks with this weapon deal 1d4 bludgeoning damage. [Properties: Ammunition (range 30/120)]',
        iconSource: './images/Item_Shop/Items/Weapons/sling.png',
        source: "Official",
        itemCost: 1,
        type: "Weapon",
    },
    "Battleaxe": {
        title: 'Battleaxe',
        body: 'A large, double-bladed axe. Attacks with this weapon deal 1d8 slashing damage. [Properties: Versatile (1d10)]',
        iconSource: './images/Item_Shop/Items/Weapons/battleaxe.png',
        source: "Official",
        itemCost: 1,
        type: "Weapon",
    },
    "Glaive": {
        title: 'Glaive',
        body: 'A long polearm with a menacing length of steel at one end. Attacks with this weapon deal 1d10 slashing damage. [Properties: Heavy, Reach, Two-handed]',
        iconSource: './images/Item_Shop/Items/Weapons/glaive.png',
        source: "Official",
        itemCost: 1,
        type: "Weapon",
    },
    "Longsword": {
        title: 'Longsword',
        body: 'A large, double-bladed axe. Attacks with this weapon deal 1d8 slashing damage. [Properties: Versatile (1d10)]',
        iconSource: './images/Item_Shop/Items/Weapons/longsword.png',
        source: "Official",
        itemCost: 15,
        type: "Weapon",
    },
}
